eureka:
  client:
    fetch-registry: true #by default, it was true
    register-with-eureka: true #by default, it was true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

  
